### ISSUE TITLE
Update dark-whatsapp to 2.0

### ISSUE THREAD

**Issue by bkosse** [dcferreira/franz-themes#1]
Hi,
I love to use the dark-whatsapp theme with Franz/Ferdi. Could you update to 2.0?

**Comment by Stanzilla** [comment]
Yup, need help with porting over something maybe? Willing to contribute!

**Comment by vednoc** [comment]
@dcferreira @bkosse @Stanzilla (Sorry for pinging!)

I just released [wa.user.css version](https://github.com/vednoc/dark-whatsapp/blob/master/wa.user.css) and a script to convert it to `darktheme.css`, but the script is untested - let me know if you encounter any issues.

The simplest way to use it would be:
```shell
$ pwd
/home/user/.config/Ferdi/recipes/

git clone https://github.com/vednoc/dark-whatsapp whatsapp

cd whatsapp

./whatsapp.sh
```
If the script doesn't execute, you might need to do `chmod +x whatsapp.sh` first.

The update is currently manual, you'll have to `git pull` and re-run the script. Also, there are files that are in unstaged state so it'd be nice to have them all added to the `.gitignore` file.

I kinda plan to automate it in future versions, but I'm a total newb at shell scripting so it'll take some time. Hope you guys enjoy! :smiley: 

Obligatory screenshot: 
![image](https://user-images.githubusercontent.com/18245694/72855703-a4843c00-3cb8-11ea-84e1-377a2e4f07eb.png)

**Comment by vednoc** [comment]
There seems to be an issue on Ferdi - the app window ends up not having 19px gap at the top and bottom. It can be fixed by adding this snippet at the end of `darktheme.css`:
```css
#app .app-wrapper-web .app {
    top: 19px !important;
    height: calc(100% - 36px) !important;
}

**Comment by dcferreira** [comment]
Sorry for taking so long, somehow I missed the notifications for this issue.
It's now updated, thanks to @vednoc 's script :)

**Comment by Stanzilla** [comment]
macOS does not support head with a negative number, otherwise the script seems to work fine @vednoc

**Comment by vednoc** [comment]
Thank you @Stanzilla for letting me know about it. I'll figure out a different solution. :smiley:
