### ISSUE TITLE
Remove output from whatsapp.sh

### ISSUE THREAD

**Issue by vednoc** [dcferreira/franz-themes#5]
Hey @dcferreira,

You might want to remove these [two lines][0] that are coming from the latest update to [whatsapp.sh][0].

I think the best workaround is to redirect STDOUT (or maybe STDERR as well) to /dev/null in your [update][2] script with something like `./whatsapp.sh 1>/dev/null`; I just learned I need to redirect my `echo` to STDERR in case the file can't be found. :smile: 

[0]: 
https://github.com/dcferreira/franz-themes/blob/c88bab4865a2969da6a5e80aa5df947da3b80836/whatsapp/darkmode.css#L1-L2
[1]: https://github.com/vednoc/dark-whatsapp/commit/bc39d0c8f489901c93fe620e42adcd2840361799
[2]: https://github.com/dcferreira/franz-themes/blob/843a77f461115a71f2a8a2e1bc35cd13e7e30557/whatsapp/update.sh

**Comment by dcferreira** [comment]
Hi @vednoc, thanks for the message.
I did just that in 9483ef22b75f46e306f35cb2e66970f48a54f525 as you were commenting :P

That's what I get for not testing before pushing. But it's fixed now :)

**Comment by vednoc** [comment]
Awesome! I guess I should've refreshed the repository for updates before posting the issue. :sweat_smile:
